from django.urls import path,include
from . import views


urlpatterns=[
    path('',views.Main.as_view(),name='main'),
    path('login/',views.Login.as_view(),name='login'),
    path('register/',views.Register.as_view(),name='register'),
    path('dashboard/',views.Dashboard.as_view(),name='dashboard'),
    path('order/',views.Order.as_view(),name='order'),
    path('applications/',views.Applications.as_view(),name='apply'),
    path('staff/',views.Staff.as_view(),name='staff'),
    path('rezident/',views.RezidentView.as_view(),name='rezident'),
    path('rezident/create',views.Rezident_Create.as_view(),name='create_rez'),
    path('money/',views.Money.as_view(),name='money'),
    path('money/create',views.Money_Create.as_view(),name='create_money'),
    path('debt/',views.Debt.as_view(),name='debt'),
    path('warehouse/',views.WarehouseView.as_view(),name='warehouse'),
    path('warehouse/create', views.WarehouseCreateView.as_view(),name='warehouse_create'),
    path('warehouse/limit',views.WarehouseLimitView.as_view(),name='warehouse_limit'),
    path('telegram_webhook/',views.telegram_webhook,name='telegram_webhook'),
    path('order/<int:pk>',views.OrderDetail.as_view(),name='order_detail'),
    path('logout/',views.logout_view,name='logout'),
    path('profile',views.ProfileView.as_view(),name='profile'),
    path('clients/',views.ClietView.as_view(),name='clients'),
    path('clients/add',views.ClientCreateView.as_view(),name='client_add'),
    path('search-client/', views.search_client, name='search-client'),
    path('staff/more',views.Staff_more.as_view(),name='staff_more'),
    path('staff/archive',views.StaffArchive.as_view(),name='staff_archive'),
    path('marketing/',views.MarketingClietView.as_view(),name='marketing'),
    path('marketing/add',views.MarketingClientCreateView.as_view(),name='marketing_add'),
    path('marketing/<int:pk>',views.DetailMarketing.as_view(),name='marketing_detail'),
    path('archive/',views.ArchiveOrder.as_view(),name='archive'),
    path('call_center/',views.Call_center.as_view(),name='call_center'),
    path('call_center/add',views.Call_center_add.as_view(),name='call_center_add'),
    path('call_center/<int:pk>',views.DetailCall.as_view(),name='call_cente_detail'),
    path('my_projects/',views.MyProjects.as_view(),name='my_projects'),
    path('search-profile/', views.search_profiles, name='search-profile'),
    path('assign/', views.assign_project, name='assign'),
    path('provider/',views.ProviderView.as_view(),name='provider'),
    path('provider/add',views.ProvideCreateView.as_view(),name='provider_add'),
    path('finance-profile/',views.FinanceProfileView.as_view(),name='finance_profile'),
    path('notify/<int:pk>',views.NotificationVIew.as_view(),name='notify')
]