# Generated by Django 4.1.2 on 2025-03-30 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('catigories', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='postion',
        ),
        migrations.AddField(
            model_name='profile',
            name='approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('manager', 'Менеджер'), ('admin', 'Администратор'), ('supplier', 'Снабженец'), ('chief', 'Главный ЦЕХа'), ('installer', 'Установщик'), ('technologist', 'Технолог'), ('designer', 'Дизайнер')], default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=250)),
                ('adress', models.CharField(max_length=250)),
                ('order_sum', models.IntegerField(default=0)),
                ('order_predoplata', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('social', models.CharField(max_length=60)),
                ('add_order', models.DateField()),
                ('complete_order', models.DateField()),
                ('consumables', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='backend.consumables')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='backend.stage')),
            ],
        ),
    ]
