# Generated by Django 4.1.2 on 2025-03-30 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_consumables_stage_remove_profile_postion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='consumables',
        ),
        migrations.AddField(
            model_name='consumables',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consumables', to='backend.orders'),
            preserve_default=False,
        ),
    ]
