# Generated by Django 4.2.4 on 2025-04-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_warehouse_alter_consumables_price_alter_finance_sum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='created_at',
            field=models.DateField(),
        ),
    ]
