# Generated by Django 4.2.4 on 2025-04-10 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_warehouse_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='price',
        ),
    ]
