# Generated by Django 4.2.4 on 2025-04-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_remove_warehouse_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=70)),
                ('product', models.CharField(max_length=70)),
                ('limit', models.IntegerField(default=0)),
            ],
        ),
    ]
