# Generated by Django 4.2.4 on 2025-04-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_warehouselimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='stage',
            field=models.CharField(choices=[('manager', 'Принят'), ('admin', 'Проектирование'), ('supplier', 'Производство'), ('chief', 'Сборка'), ('installer', 'Доставка'), ('technologist', 'Завершён')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
    ]
