# Generated by Django 4.2.4 on 2025-04-11 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_orders_stage_delete_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='category',
        ),
    ]
