# Generated by Django 4.2.4 on 2025-04-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_alter_orders_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='stage',
            field=models.CharField(choices=[('accepted', 'Принят'), ('design', 'Проектирование'), ('technologist', 'Технолог'), ('manufacturing', 'Производство'), ('assembly', 'Сборка'), ('delivery', 'Доставка'), ('order_ready', 'Заказ готов'), ('finished', 'Завершено')], max_length=20),
        ),
    ]
