# Generated by Django 4.2.4 on 2025-04-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_orders_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_predoplata',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
