# Generated by Django 4.2.4 on 2025-04-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_orders_order_predoplata'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='fill',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='print',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='rezka',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='sborka',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='svarka',
            field=models.BooleanField(default=False),
        ),
    ]
