# Generated by Django 4.2.4 on 2025-04-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_orders_fill_orders_print_orders_rezka_orders_sborka_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='delivery_photo',
            field=models.ImageField(blank=True, upload_to='delivery/'),
        ),
    ]
