# Generated by Django 4.2.4 on 2025-04-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_orders_delivery_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery_photo',
            field=models.ImageField(blank=True, upload_to='delivery/'),
        ),
    ]
