# Generated by Django 4.2.4 on 2025-04-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_alter_orders_delivery_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='sborka',
        ),
        migrations.AddField(
            model_name='orders',
            name='stage_pod',
            field=models.CharField(choices=[('rezka', 'Резка'), ('svarka', 'Сварка'), ('fill', 'Покраска'), ('print', 'Печать')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
