# Generated by Django 4.2.4 on 2025-04-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_remove_orders_sborka_orders_stage_pod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='stage_pod',
            field=models.CharField(choices=[('rezka', 'Резка'), ('svarka', 'Сварка'), ('fill', 'Покраска'), ('print', 'Печать')], default='rezka', max_length=20),
        ),
    ]
