# Generated by Django 4.2.4 on 2025-04-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0022_alter_orders_stage_pod'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='payment_data',
            field=models.DateField(null=True),
        ),
    ]
