# Generated by Django 4.1.2 on 2025-04-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_orders_payment_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumables',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
