# Generated by Django 4.2.4 on 2025-04-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_consumables_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='complete_photo',
            field=models.ImageField(blank=True, upload_to='complete/'),
        ),
    ]
