# Generated by Django 4.2.4 on 2025-04-25 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_orders_complete_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='complete_photo',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='delivery_photo',
        ),
        migrations.CreateModel(
            name='Delivery_Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='delivery/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_photo', to='backend.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Compelete_Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='complete/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complete_photo', to='backend.orders')),
            ],
        ),
    ]
