# Generated by Django 4.2.4 on 2025-04-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_remove_orders_complete_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='complete_date',
            field=models.DateField(null=True),
        ),
    ]
