# Generated by Django 4.2.4 on 2025-04-28 07:53

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_orders_complete_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telegram_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('chat_id', models.IntegerField(default=0)),
            ],
        ),
    ]
