# Generated by Django 4.1.2 on 2025-06-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_telegram_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='stage',
            field=models.CharField(choices=[('accepted', 'Принят'), ('design', 'Проектирование'), ('technologist', 'Технолог'), ('manufacturing', 'Производство'), ('assembly', 'Сборка'), ('delivery', 'Доставка'), ('order_ready', 'Заказ готов'), ('finished', 'Завершён')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(choices=[('manager', 'Менеджер'), ('admin', 'Администратор'), ('accountant', 'Бухгалтер'), ('supplier', 'Снабженец'), ('chief', 'Главный ЦЕХа'), ('chief_staff', 'Сотрудник ЦЕХа'), ('delivery_cheif', 'Главный доставщик'), ('delivery', 'Доставщик'), ('installer_cheif', 'Главный установщик'), ('installer', 'Установщик'), ('technologist_cheif', 'Главный Технолог'), ('technologist', 'Технолог'), ('designer_cheif', 'Главный дизайнер'), ('designer', 'Дизайнер'), ('qa_cheif', 'Главный сотрудник контроля качества'), ('qa_staff', 'Сотрудник контроля качества'), ('sales_marketing', 'Соц. маркетолог'), ('sales_call', 'Сотрудник колл-центра')], max_length=20),
        ),
    ]
