# Generated by Django 4.2.4 on 2025-06-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0031_alter_orders_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='stage',
            field=models.CharField(choices=[('marketing', 'Соц. маркетинг'), ('call_center', 'Колл-центр'), ('manager', 'Менеджер'), ('design', 'Проектирование'), ('technologist', 'Технолог'), ('manager_2', 'Менеджер_2'), ('accounting', 'Бухгалтерия'), ('warehouse', 'Склад'), ('manufacturing', 'Производство'), ('assembly_stage', 'Сборка'), ('accounting_2', 'Бухгалтерия_2'), ('delivery', 'Доставка'), ('installation', 'Установка'), ('quality_control', 'Контроль качества'), ('finished', 'Завершён'), ('archive', 'Архив')], max_length=20),
        ),
    ]
