# Generated by Django 4.2.4 on 2025-06-21 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_alter_orders_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='client',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='social',
        ),
    ]
