# Generated by Django 4.2.4 on 2025-06-22 02:56

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_remove_orders_adress_remove_orders_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social', models.CharField(choices=[('social', 'Социальные сети'), ('cold_calls', 'Холодные звонки'), ('word_of_mouth', 'Сарафанное радио')], max_length=20)),
                ('client_type', models.CharField(choices=[('INDIVIDUAL', 'Физическое лицо'), ('LEGAL_ENTITY', 'Юридическое лицо')], max_length=20)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('lastname', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('middle_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('adress', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('company_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('inn', models.CharField(blank=True, default=None, max_length=12, null=True)),
                ('account', models.IntegerField(blank=True, default=None, null=True)),
                ('mfo', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
    ]
