# Generated by Django 4.2.4 on 2025-06-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
