# Generated by Django 4.2.4 on 2025-06-22 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0035_clients_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients_order', to='backend.clients'),
        ),
    ]
