# Generated by Django 4.1.2 on 2025-06-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_orders_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='vstrecha',
            field=models.CharField(choices=[('viezd', 'Выезд'), ('priezd', 'Приезд')], max_length=20, null=True),
        ),
    ]
