# Generated by Django 4.1.2 on 2025-06-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_orders_vstrecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='catigories',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='razmer',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
