# Generated by Django 4.1.2 on 2025-06-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0038_orders_catigories_orders_razmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='latitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='longitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
