# Generated by Django 4.1.2 on 2025-06-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_orders_latitude_orders_longitude_orders_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='design',
            field=models.FileField(blank=True, upload_to='pictures/'),
        ),
        migrations.AddField(
            model_name='orders',
            name='tz',
            field=models.FileField(blank=True, upload_to='pictures/'),
        ),
    ]
