# Generated by Django 4.1.2 on 2025-06-26 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_orders_design_orders_tz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='phone',
        ),
    ]
