# Generated by Django 4.1.2 on 2025-06-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0041_remove_orders_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='check_design',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='description_design',
            field=models.TextField(default='beka'),
            preserve_default=False,
        ),
    ]
