# Generated by Django 4.1.2 on 2025-06-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0042_orders_check_design_orders_description_design'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
