# Generated by Django 4.1.2 on 2025-06-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_profile_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='archive',
            field=models.BooleanField(default=True),
        ),
    ]
