# Generated by Django 4.1.2 on 2025-07-01 18:01

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0045_social_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='social_clients',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marketing', to='backend.orders'),
        ),
        migrations.AlterField(
            model_name='social_clients',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='social_clients',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True, region=None),
        ),
    ]
