# Generated by Django 4.1.2 on 2025-07-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0046_social_clients_order_alter_social_clients_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='stage',
            field=models.CharField(choices=[('marketing', 'Соц. маркетинг'), ('call_center', 'Колл-центр'), ('manager', 'Менеджер'), ('design', 'Проектирование'), ('technologist', 'Технолог'), ('manager_2', 'Менеджер_2'), ('accounting', 'Бухгалтерия'), ('warehouse', 'Склад'), ('manufacturing', 'Производство'), ('assembly_stage', 'Сборка'), ('accounting_2', 'Бухгалтерия_2'), ('delivery', 'Доставка'), ('installation', 'Установка'), ('quality_control', 'Контроль качества'), ('finished', 'Завершён'), ('archive', 'Архив')], default='marketing', max_length=20),
        ),
    ]
