# Generated by Django 4.1.2 on 2025-07-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0047_alter_orders_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='add_order',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='complete_order',
            field=models.DateField(null=True),
        ),
    ]
