# Generated by Django 4.1.2 on 2025-07-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0049_alter_orders_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='fail',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
