# Generated by Django 4.1.2 on 2025-07-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0050_orders_fail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='by_who_fail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='fail_date',
            field=models.DateField(null=True),
        ),
    ]
