# Generated by Django 4.1.2 on 2025-07-03 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0051_orders_by_who_fail_orders_fail_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='call_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_center_profile', to='backend.profile', verbose_name='Профиль'),
        ),
    ]
