# Generated by Django 4.1.2 on 2025-07-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0052_orders_call_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='zayavki',
            field=models.CharField(choices=[('hot', 'Горячая'), ('cool', 'Холодная')], max_length=20, null=True),
        ),
    ]
