# Generated by Django 4.1.2 on 2025-07-03 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0053_orders_zayavki'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
