# Generated by Django 4.1.2 on 2025-07-06 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0054_clients_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='completed_by_desinger',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='designer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designer_profile', to='backend.profile', verbose_name='Профиль'),
        ),
    ]
