# Generated by Django 4.1.2 on 2025-07-07 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0055_orders_completed_by_desinger_orders_designer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='completed_by_technolgy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orders',
            name='technolgy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technolgy_profile', to='backend.profile', verbose_name='Профиль'),
        ),
    ]
