# Generated by Django 4.1.2 on 2025-07-07 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0056_orders_completed_by_technolgy_orders_technolgy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumables',
            name='catigories',
        ),
        migrations.RemoveField(
            model_name='consumables',
            name='price',
        ),
    ]
