# Generated by Django 4.1.2 on 2025-07-08 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0057_remove_consumables_catigories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_by_desinger', models.BooleanField(default=False)),
                ('completed_by_technolgy', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_staff', to='backend.orders')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_profile', to='backend.profile', verbose_name='Профиль')),
            ],
        ),
    ]
