# Generated by Django 4.1.2 on 2025-07-08 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0058_orderstaff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='designer',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='technolgy',
        ),
    ]
