# Generated by Django 4.1.2 on 2025-07-08 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0059_remove_orders_designer_remove_orders_technolgy'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='designer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designer_profile', to='backend.profile', verbose_name='Профиль'),
        ),
        migrations.AddField(
            model_name='orders',
            name='technolgy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technolgy_profile', to='backend.profile', verbose_name='Профиль'),
        ),
    ]
