# Generated by Django 4.1.2 on 2025-07-08 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0060_orders_designer_orders_technolgy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderstaff',
            old_name='completed_by_desinger',
            new_name='complete',
        ),
        migrations.RenameField(
            model_name='orderstaff',
            old_name='completed_by_technolgy',
            new_name='upload',
        ),
        migrations.AlterField(
            model_name='orders',
            name='call_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call_center_profile', to='backend.profile', verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='designer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designer_profile', to='backend.profile', verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='technolgy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technolgy_profile', to='backend.profile', verbose_name='Профиль'),
        ),
    ]
