# Generated by Django 4.1.2 on 2025-07-10 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0061_rename_completed_by_desinger_orderstaff_complete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='completed_by_desinger',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='completed_by_technolgy',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='designer',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='technolgy',
        ),
    ]
