# Generated by Django 4.1.2 on 2025-07-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0062_remove_orders_completed_by_desinger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumables',
            name='warehouse',
            field=models.BooleanField(default=False),
        ),
    ]
