# Generated by Django 4.1.2 on 2025-07-10 13:03

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0063_consumables_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('lastname', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('middle_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
    ]
