# Generated by Django 4.1.2 on 2025-07-10 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0064_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='deliver',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider', to='backend.provider'),
        ),
    ]
