# Generated by Django 4.1.2 on 2025-07-15 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0067_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
    ]
