# Generated by Django 4.1.2 on 2025-07-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0068_remove_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstaff',
            name='fill',
            field=models.CharField(choices=[('no', 'no'), ('chief', 'chief'), ('staff', 'staff')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='orderstaff',
            name='print',
            field=models.CharField(choices=[('no', 'no'), ('chief', 'chief'), ('staff', 'staff')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='orderstaff',
            name='rezka',
            field=models.CharField(choices=[('no', 'no'), ('chief', 'chief'), ('staff', 'staff')], default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='orderstaff',
            name='svarka',
            field=models.CharField(choices=[('no', 'no'), ('chief', 'chief'), ('staff', 'staff')], default='no', max_length=20),
        ),
    ]
