# Generated by Django 4.1.2 on 2025-07-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0069_orderstaff_fill_orderstaff_print_orderstaff_rezka_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='sborka',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orders',
            name='stage_pod',
            field=models.CharField(choices=[('rezka', 'Резка'), ('svarka', 'Сварка'), ('fill', 'Покраска'), ('print', 'Печать'), ('sborka', 'Сборка'), ('ready', 'Готово')], default='rezka', max_length=20),
        ),
    ]
