# Generated by Django 4.1.2 on 2025-07-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0070_orders_sborka_alter_orders_stage_pod'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstaff',
            name='sborka',
            field=models.CharField(choices=[('no', 'no'), ('chief', 'chief'), ('staff', 'staff')], default='no', max_length=20),
        ),
    ]
