# Generated by Django 4.1.2 on 2025-07-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0071_orderstaff_sborka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='stage',
            field=models.CharField(choices=[('marketing', 'Соц. маркетинг'), ('call_center', 'Колл-центр'), ('manager', 'Менеджер'), ('design', 'Проектирование'), ('technologist', 'Технолог'), ('manager_2', 'Менеджер_2'), ('accounting', 'Бухгалтерия'), ('warehouse', 'Склад'), ('manufacturing', 'Производство'), ('accounting_2', 'Бухгалтерия_2'), ('delivery', 'Доставка'), ('installation', 'Установка'), ('quality_control', 'Контроль качества'), ('finished', 'Завершён'), ('archive', 'Архив'), ('failed', 'fail')], default='manager', max_length=20),
        ),
    ]
