# Generated by Django 4.1.2 on 2025-07-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0072_alter_orders_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
