# Generated by Django 4.1.2 on 2025-07-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0073_warehouse_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='approve_accounting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='salary_black',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='salary_pure',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
