# Generated by Django 4.1.2 on 2025-07-20 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0074_profile_approve_accounting_profile_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shtraff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('summa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shtraff_profile', to='backend.profile', verbose_name='Профиль')),
            ],
        ),
    ]
