# Generated by Django 4.1.2 on 2025-07-22 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0075_shtraff'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='position',
            field=models.CharField(choices=[('manager', 'Менеджер'), ('accountant', 'Бухгалтер'), ('supplier', 'Снабженец'), ('chief', 'Главный ЦЕХа'), ('chief_staff', 'Сотрудник ЦЕХа'), ('delivery_cheif', 'Главный доставщик'), ('delivery', 'Доставщик'), ('installer_cheif', 'Главный установщик'), ('installer', 'Установщик'), ('technologist_cheif', 'Главный Технолог'), ('technologist', 'Технолог'), ('designer_cheif', 'Главный дизайнер'), ('designer', 'Дизайнер'), ('qa_cheif', 'Главный сотрудник контроля качества'), ('qa_staff', 'Сотрудник контроля качества'), ('sales_call', 'Сотрудник колл-центра')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_notifcation', to='backend.profile', verbose_name='Профиль'),
        ),
    ]
