# Generated by Django 4.1.2 on 2025-07-22 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0076_notification_position_alter_notification_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='position',
            new_name='stage',
        ),
    ]
