# Generated by Django 4.1.2 on 2025-07-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0078_alter_notification_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
