# Generated by Django 4.1.2 on 2025-07-23 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0080_alter_notification_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='stage',
            field=models.CharField(choices=[('call_center', 'Колл-центр'), ('call_center_back', 'Колл-центр_назад'), ('manager', 'Менеджер'), ('manager_qa', 'Менеджер_встреча'), ('design', 'Проектирование'), ('technologist', 'Технолог'), ('manager_2', 'Менеджер_2'), ('accounting', 'Бухгалтерия'), ('warehouse', 'Склад'), ('manufacturing', 'Производство'), ('accounting_2', 'Бухгалтерия_2'), ('delivery', 'Доставка'), ('installation', 'Установка'), ('quality_control', 'Контроль качества')], max_length=20, null=True),
        ),
    ]
