# Generated by Django 4.1.2 on 2025-07-23 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0081_alter_notification_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='stage',
            field=models.CharField(choices=[('call_center', 'Колл-центр'), ('call_center_back', 'Колл-центр_назад'), ('manager', 'Менеджер'), ('manager_qa', 'Менеджер_встреча'), ('manager_qa_back', 'Менеджер_встреча_назад'), ('design', 'Проектирование'), ('technologist', 'Технолог'), ('manager_2', 'Менеджер_2'), ('accounting', 'Бухгалтерия'), ('warehouse', 'Склад'), ('manufacturing', 'Производство'), ('accounting_2', 'Бухгалтерия_2'), ('delivery', 'Доставка'), ('installation', 'Установка'), ('quality_control', 'Контроль качества')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Manager_Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='manager/')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_photo', to='backend.notification')),
            ],
        ),
    ]
