# Generated by Django 4.1.2 on 2025-07-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0082_alter_notification_stage_manager_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager_photo',
            name='photo',
            field=models.FileField(blank=True, upload_to='manager/'),
        ),
    ]
