# Generated by Django 4.1.2 on 2025-07-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0083_alter_manager_photo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstaff',
            name='back',
            field=models.BooleanField(default=False),
        ),
    ]
