# Generated by Django 4.1.2 on 2025-07-25 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0084_orderstaff_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='backend.orders'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='stage',
            field=models.CharField(choices=[('zayavki', 'Заявки'), ('call_center', 'Колл-центр'), ('call_center_back', 'Колл-центр_назад'), ('manager', 'Менеджер'), ('manager_qa', 'Менеджер_встреча'), ('manager_qa_back', 'Менеджер_встреча_назад'), ('design', 'Проектирование'), ('technologist', 'Технолог'), ('manager_2', 'Менеджер_2'), ('accounting', 'Бухгалтерия'), ('warehouse', 'Склад'), ('manufacturing', 'Производство'), ('accounting_2', 'Бухгалтерия_2'), ('delivery', 'Доставка'), ('installation', 'Установка'), ('quality_control', 'Контроль качества'), ('back', 'Назад'), ('finished', 'Завершён')], max_length=20, null=True),
        ),
    ]
