# Generated by Django 4.1.2 on 2025-07-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0085_alter_notification_order_alter_notification_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
