# Generated by Django 4.1.2 on 2025-08-01 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0086_notification_complete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('payment', 'Пополнение'), ('withdraw', 'Вывод'), ('fail', 'Отклонено'), ('shtraff', 'Штраф')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('summa', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='backend.profile', verbose_name='Профиль')),
            ],
        ),
        migrations.DeleteModel(
            name='Shtraff',
        ),
    ]
