# Generated by Django 4.2.4 on 2025-08-06 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0087_payments_delete_shtraff'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='profile_chief',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_as_chief', to='backend.profile', verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_notifcation', to='backend.profile', verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='stage',
            field=models.CharField(choices=[('zayavki', 'Заявки'), ('call_center', 'Колл-центр'), ('call_center_back', 'Колл-центр_назад'), ('manager', 'Менеджер'), ('manager_qa', 'Менеджер_встреча'), ('manager_qa_back', 'Менеджер_встреча_назад'), ('design', 'Проектирование'), ('technologist', 'Технолог'), ('manager_2', 'Менеджер_2'), ('accounting', 'Бухгалтерия'), ('warehouse', 'Склад'), ('manufacturing', 'Производство'), ('accounting_2', 'Бухгалтерия_2'), ('delivery', 'Доставка'), ('installation', 'Установка'), ('quality_control', 'Контроль качества'), ('back', 'Назад'), ('finished', 'Завершён'), ('payment_chief', 'payment_chief'), ('payment_manager', 'payment_manager')], max_length=20, null=True),
        ),
    ]
