# Generated by Django 4.2.4 on 2025-08-06 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0088_notification_profile_chief_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='profile_chief',
        ),
    ]
